# reusable workflow to install NPM dependencies
# and run Cypress tests across N machines in parallel
name: parallel
on:
  workflow_call:
    inputs:
      n:
        description: 'Number of parallel containers'
        type: number
        required: true
        default: 1

jobs:
  prepare:
    runs-on: ubuntu-20.04
    # explicitly set the output of this job
    # so that other jobs can use it
    outputs:
      matrix: ${{ steps.prepare.outputs.matrix }}
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v2

      # generate the list using a bash script
      - name: Create matrix ⊹
        id: prepare
        # for reusable workflow, must use the full action reference
        uses: bahmutov/gh-build-matrix@main
        with:
          n: ${{ inputs.n }} # number of containers to output

      - name: Print result 🖨
        run: echo '${{ steps.prepare.outputs.matrix }}'
