# reusable workflow to install NPM dependencies
# and run Cypress tests across N machines in parallel
# https://docs.github.com/en/actions/learn-github-actions/reusing-workflows
name: parallel
on:
  workflow_call:
    inputs:
      n:
        description: 'Number of parallel containers'
        type: number
        required: true
        default: 1
    secrets:
      recordKey:
        description: 'Cypress Dashboard Record Key'
        required: true

jobs:
  prepare:
    runs-on: ubuntu-20.04
    # explicitly set the output of this job
    # so that other jobs can use it
    outputs:
      matrix: ${{ steps.prepare.outputs.matrix }}
    steps:
      # generate the list using a bash script
      - name: Create matrix ⊹
        id: prepare
        # for reusable workflow, must use the full action reference
        uses: bahmutov/gh-build-matrix@main
        with:
          n: ${{ inputs.n }} # number of containers to output

      - name: Print result 🖨
        run: echo '${{ steps.prepare.outputs.matrix }}'

  # the N parallel testing jobs we create
  # https://github.com/cypress-io/github-action#parallel
  test:
    needs: prepare
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix: ${{fromJSON(needs.prepare.outputs.matrix)}}
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v2

      # because of "record" and "parallel" parameters
      # these containers will load balance all found tests among themselves
      - name: Cypress tests 🧪
        uses: cypress-io/github-action@v2
        with:
          record: true
          parallel: true
          group: 'Parallel tests'
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.recordKey }}
